# Generated by Django 5.2.7 on 2025-10-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchupDescription',
            fields=[
                ('matchup_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('song_a', models.CharField(max_length=2000)),
                ('song_b', models.CharField(max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
