# Generated by Django 5.2.15 on 2026-06-15 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchup',
            options={'ordering': ['round_number', 'matchup_num']},
        ),
        migrations.RenameField(
            model_name='matchup',
            old_name='matchup_number',
            new_name='matchup_num',
        ),
        migrations.AlterField(
            model_name='bracket',
            name='owner',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='brackets',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
