# Generated by Django 5.2.15 on 2026-06-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0002_alter_matchup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='next_slot',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
