# Generated by Django 5.2.15 on 2026-06-25 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0003_matchup_next_slot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(default=1)),
                ('current_round_progress', models.FloatField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_brackets', to='brackets.bracket')),
                ('champion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_bracket_championships', to='brackets.bracketitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_brackets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMatchupPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matchup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_picks', to='brackets.matchup')),
                ('user_bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='brackets.userbracket')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_matchup_wins', to='brackets.bracketitem')),
            ],
        ),
        migrations.AddConstraint(
            model_name='userbracket',
            constraint=models.UniqueConstraint(fields=('user', 'bracket'), name='unique_user_bracket_per_template'),
        ),
        migrations.AddConstraint(
            model_name='usermatchuppick',
            constraint=models.UniqueConstraint(fields=('user_bracket', 'matchup'), name='unique_pick_per_user_matchup'),
        ),
    ]
